### ISSUE TITLE
thinkboxcm library ?

### ISSUE THREAD

**Issue by nyue** [aws/thinkbox-krakatoa#1]
Hi,

  There appears to be some dependencies that are not included or exists as submodule ?

  Any advice ?

Cheers

**Comment by RandomInsano** [comment]
There are quite a few libraries. That one is available. Take a look here:

https://github.com/orgs/aws/repositories?q=Thinkbox&type=all&language=&sort=

**Comment by nyue** [comment]
@RandomInsano Thanks for pointing that out. I will create a superbuild to tie in all the dependencies.

**Comment by RandomInsano** [comment]
I haven’t dug into how to build things just yet but the announcement Evan put on the forums might be a good start in understanding the dependencies:

https://forums.thinkboxsoftware.com/t/thinkbox-artist-tools-open-source-release/29947

**Comment by evanspearman-a** [comment]
The forums post that Edwin linked is definitely a good place to start as it gives an overview of the dependency tree and what each repository contains.

The CONTRIBUTING.md files in each repository should also list the individual dependencies of a given project and provide links.

For Krakatoa itself though it will be:

```
thinkbox-cm-library (https://github.com/aws/thinkbox-cm-library)
|
v
thinkbox-library (https://github.com/aws/thinkbox-library)
|
v
thinkbox-krakatoa/Krakatoa
|
v
thinkbox-krakatoa/KrakatoaSR
```

The easiest workflow is to clone the repository of the dependency and run `build.py` (requires Python 3.10+, `conan`, and `conan_package_tools` from pip), which will build all variants of a given library and put them in your local Conan cache.

**Comment by evanspearman-a** [comment]
I believe this has been answered so I'm going to close it. Feel free to create a new issue if you have any more questions.
